language: php

sudo: false

cache:
  directories:
    - build/reports

php:
  - 7.4
  - 7.3
  - 7.1
  - 7.0
  - 5.6

matrix:
  fast_finish: true

# We only build pushes to master and pull requests
branches:
  only:
    - master

install:
  - mkdir -p build/reports

script:
  - php test.php >> build/reports/report-$(phpenv version-name).html

after_success:
  - ls build/reports