language: php
os: linux

cache:
  directories:
    - build/reports

php:
  - 7.4
  - 7.3
  - 7.1
  - 7.0

# We only build pushes to master and pull requests
branches:
  only:
    - master

install:
  - mkdir -p build/reports

script:
  - php reports.php > build/reports/report-$(phpenv version-name).html

after_success:
  - cat build/reports